//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Exam
    {
        public string Exam_Type { get; set; }
        public int Exam_Id { get; set; }
        public string Exam_Title { get; set; }
        public string Categorie { get; set; }
        public string Sub_Categorie { get; set; }
        public Nullable<int> Num_Questions { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Is_Optional { get; set; }
        public string Is_True_orFalse { get; set; }
        public Nullable<int> TimeDuration { get; set; }
    }
}
