//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Courses
    {
        public int id { get; set; }
        public string add_coures { get; set; }
        public string duration { get; set; }
        public Nullable<int> fees { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
