//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_tbl_Answer
    {
        public int Ans_ID { get; set; }
        public Nullable<int> Attempted_Id { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Creted_By { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
