//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Payment
    {
        public int Payment_Id { get; set; }
        public Nullable<System.DateTime> Pay_Date { get; set; }
        public string Pay_Method { get; set; }
        public string Pay_Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
