//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Login
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string UserName { get; set; }
    }
}
