//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Score
    {
        public Nullable<int> Exam_id { get; set; }
        public int Question_NO { get; set; }
        public string Question { get; set; }
        public string Opction1 { get; set; }
        public string Opction2 { get; set; }
        public string Opction3 { get; set; }
        public string Opction4 { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
