//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Institute
    {
        public string name { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public string Address { get; set; }
        public string YourEducation { get; set; }
        public string Institute_type { get; set; }
        public string Present_job_profession { get; set; }
        public string Education_Sector_Experience { get; set; }
        public string Your_Comment_query { get; set; }
        public Nullable<System.DateTime> createdone { get; set; }
        public string createdby { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public string opdatedby { get; set; }
        public int id { get; set; }
        public string Institute_Pre_School { get; set; }
        public Nullable<bool> isapprove { get; set; }
    }
}
