//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IWS_Student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string lst_class { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string course_name { get; set; }
        public string cast { get; set; }
        public string religion { get; set; }
        public string address { get; set; }
        public Nullable<long> aadhar_NO { get; set; }
        public Nullable<long> whats_no_self { get; set; }
        public Nullable<long> whats_no_home { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<long> refid { get; set; }
        public string images { get; set; }
        public string img_sing { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> institute_id { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public Nullable<bool> isApprove { get; set; }
        public string Year { get; set; }
        public string Status { get; set; }
    }
}
