//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEC_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IWSSLSEEntities : DbContext
    {
        public IWSSLSEEntities()
            : base("name=IWSSLSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IWS_Categories> IWS_Categories { get; set; }
        public virtual DbSet<IWS_Courses> IWS_Courses { get; set; }
        public virtual DbSet<IWS_Exam> IWS_Exam { get; set; }
        public virtual DbSet<IWS_Institute> IWS_Institute { get; set; }
        public virtual DbSet<IWS_Login> IWS_Login { get; set; }
        public virtual DbSet<IWS_Score> IWS_Score { get; set; }
        public virtual DbSet<IWS_Student> IWS_Student { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<IWS_Payment> IWS_Payment { get; set; }
        public virtual DbSet<IWS_Exam_login> IWS_Exam_login { get; set; }
        public virtual DbSet<IWS_Exam_Histroy> IWS_Exam_Histroy { get; set; }
        public virtual DbSet<IWS_tbl_Answer> IWS_tbl_Answer { get; set; }
    }
}
